name: 'Bump Version'

on:
    push:
        branches:
            - 'master'

jobs:
    bump-version:
        name: 'Bump Version on master'
        runs-on: ubuntu-latest
        if: "!contains(github.event.head_commit.message, '[SKIP]')"

        steps:
            - name: 'Checkout source code'
              uses: 'actions/checkout@v2.3.4'
              with:
                  ref: ${{ github.ref }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Setup Node.js'
              uses: 'actions/setup-node@v2.1.5'
              with:
                  node-version: 15
            - name: 'Automated Version Bump'
              id: version-bump
              uses: 'phips28/gh-action-bump-version@master'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            - name: 'cat package.json'
              run: cat ./package.json
            - name: 'Output Step'
              env:
                  NEW_TAG: ${{ steps.version-bump.outputs.newTag }}
              run: echo "new tag $NEW_TAG"
