name: 'Close finished milestones'
on:
    pull_request:
        types: [closed]

jobs:
    milestone-closer:
        runs-on: ubuntu-latest
        steps:
            - uses: instantish/milestone-closer@v1.1.0
              with:
                  repo-token: ${{ secrets.REPO_PAT }}
