name: Pull Request Stats
on: [pull_request]

jobs:
  stats:
    runs-on: ubuntu-latest
    steps:
      - name: Run pull request stats
        uses: flowwer-dev/pull-request-stats@v2.0.1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repositories: 'ragaeeb/das-js'
          period: 30
          charts: true
          sort-by: 'REVIEWS'