name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main
        with:
          node-version: 19
      - name: Install modules
        with:
          node-version: 19
        run: yarn
      - name: Run Jest
        run: yarn test
        with:
          node-version: 19
